### ISSUE TITLE
Is community prompt is confusing

### ISSUE THREAD

**Issue by arpithpm** [narenaryan/Vidura#17]
There are currently two ways to tell the user that a prompt is public. 
1. "is community prompt".
2. "Is public"

For some time I did not know what is public and what is community prompt. I think it is better to display in one way.

**Comment by arpithpm** [comment]
@narenaryan ?

**Comment by narenaryan** [comment]
Agree. We should be consistent with naming. Is public is internal whereas community prompt is kind of external wording. I have no issues with having same name internally too
